language: elixir
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.4
otp_release:
  - 19.3
  - 20.3
  - 21.1
matrix:
  exclude:
    - elixir: 1.5.3
      otp_release: 21.1
    - elixir: 1.7.4
      otp_release: 19.3

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix dialyzer --halt-exit-status
  - mix coveralls.travis

# need that sweet memory for dialyzer
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
